--!strict

--[[
	@name unban
	@author driftingAurora, dullflowerr, alias; kioukaii
	@time July 3, 2026
]]

local Types = require("../../types/sharedTypes")

export type Definition = Types.Definition

local DefinitionData: Definition = {
	name = "unban",
	rank = 100,
	aliases = {},
	description = "Unbans a user ID from this server.",
	server = "unbanServer",
	args = {
		{
			name = "userId",
			type = "number",
			required = true,
		},
	},
}

return table.freeze(DefinitionData)
