return{
	Types = {
		IsSprinting = {
			WalkSpeed = 30,
			JumpPower = 50,
			Priority = 3;
			IsStun = false;
		};

		IsDiving = {
			WalkSpeed = 0,
			JumpPower = 0,
			Priority = 3;
			IsStun = false;
		};

		IsCrouching = {
			WalkSpeed = 5,
			JumpPower = 0,
			Priority = 1;
			IsStun = false;
		};

		ShiftLock = {
			WalkSpeed = 10,
			JumpPower = 50,
			Priority = 1,
			IsStun = false
		},

		Emote = {
			WalkSpeed = 8,
			JumpPower = 0,
			Priority = 1,
			IsStun = false
		},
	},
}