local TempData = {}

TempData.plrData = {

	CharacterData = { 
		Gender = "Male";
		Inventory = {};
		
		Outfit = {};
		Appearance = {};
		Body = {};
		Access = {};
		Settings = {};
	};

	PersistantData = {
		NewPlayer = true;
	};
	
	HotBar = {
		["Slot_1"] = {};
		["Slot_2"] = {};
		["Slot_3"] = {};
		["Slot_4"] = {};
		["Slot_5"] = {};
		["Slot_6"] = {};
		["Slot_7"] = {};
		["Slot_8"] = {};
		["Slot_9"] = {};
		["Slot_0"] = {};
	};
}

TempData.items_Inventory = {}; 

return TempData

